
- name: join workers to cluster
  command: 
    cmd: kubeadm join "{{ k8s['master_ip']}}":"{{ k8s['join_port'] }}" --token "{{ k8s['token'] }}" --discovery-token-ca-cert-hash "{{ k8s['discovery_token_ca_cert_hash'] }}"
    creates: /etc/kubernetes/pki/ca.crt
